image:
  tag: d6b2cf888392f4e61233cacbee0bed49109ad077
  pullSecret: registry.cs
  
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
  hosts:
  - resume.carstonschilds.ca
