replicaCount: 1

image:
  repository: gitlab.cs:4567/resume
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - resume.example.com
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
