image: docker:latest

variables: {}

before_script:
- mkdir -p ~/.kube
- echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config

stages:
- build
- deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
  - cat "$CI_SERVER_TLS_CA_FILE" >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    - |
        tee /kaniko/.docker/config.json <<EOF
        {
          "auths": {
            "$CI_REGISTRY": {
              "username":"$CI_REGISTRY_USER",
              "password":"$CI_REGISTRY_PASSWORD"
            }
          }
        }
        EOF
    - |
        /kaniko/executor \
          --context $CI_PROJECT_DIR \
          --cache=true \
          --dockerfile $CI_PROJECT_DIR/Dockerfile \
          --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG} \
          --destination $CI_REGISTRY_IMAGE:latest
  only:
    changes:
    - Dockerfile
    - src/*
    - html/*

deploy-qa:
  stage: deploy
  image:
    name: alpine/helm:2.9.0
    entrypoint: [""]
  script:
  - /usr/bin/helm upgrade resume-qa ./resume --install --recreate-pods --namespace resume --values env/qa/values.yaml
  only:
  - release/qa
  
deploy:
  stage: deploy
  image:
    name: alpine/helm:2.9.0
    entrypoint: [""]
  script:
  - /usr/bin/helm upgrade resume-prod ./resume --install --namespace resume --values env/prod/values.yaml
  only:
  - master