image: docker:latest

variables: {}

before_script:
- mkdir -p ~/.kube
- echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
- mkdir -p dist

stages:
- build
- deploy

build:
  stage: build
  tags: 
  - build
  script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - docker pull "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest" || true
  - docker build --cache-from "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest" --tag "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHA}" .
  - docker tag "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHA}" "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  - docker push "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHA}"
  - docker push "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  only:
    changes:
    - Dockerfile
    - src/*
    - html/*

deploy-qa:
  stage: deploy
  image:
    name: alpine/helm:2.9.0
    entrypoint: [""]
  tags:
  - deploy
  script:
  - /usr/bin/helm upgrade resume-qa ./chart --install --namespace resume-qa --values env/qa/values.yaml
  only:
  - release/qa
  
deploy:
  stage: deploy
  image:
    name: alpine/helm:2.9.0
    entrypoint: [""]
  tags:
  - deploy
  script:
  - /usr/bin/helm upgrade resume-prod ./chart --install --namespace resume-prod --values env/prod/values.yaml --set "image.tag=${CI_COMMIT_SHA}"
  only:
  - master