replicaCount: 1

image:
  repository: registry.cs/personal/resume
  tag: latest
  pullPolicy: Always
  pullSecret: ''

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - resume.example.com
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
